// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbrtZnA-o7jvAdZ-Q6Faa9JIGyDZ6cw6w',
    appId: '1:409210327322:web:6246d1448f62297e371ca3',
    messagingSenderId: '409210327322',
    projectId: 'amlanguage-1ae39',
    authDomain: 'amlanguage-1ae39.firebaseapp.com',
    storageBucket: 'amlanguage-1ae39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKxmJCmDdV_F7B6apHCiK4hwWnYtPAlVU',
    appId: '1:409210327322:android:f6e6240f8cb4b0af371ca3',
    messagingSenderId: '409210327322',
    projectId: 'amlanguage-1ae39',
    storageBucket: 'amlanguage-1ae39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEiQeeUsKYINSwThY3sRQtTAYWcC8qV1o',
    appId: '1:409210327322:ios:d3b49b5ec4eac4fa371ca3',
    messagingSenderId: '409210327322',
    projectId: 'amlanguage-1ae39',
    storageBucket: 'amlanguage-1ae39.appspot.com',
    iosClientId: '409210327322-16ccdbv1q0bkgdo0hej7r4voeh1ul6v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEiQeeUsKYINSwThY3sRQtTAYWcC8qV1o',
    appId: '1:409210327322:ios:d3b49b5ec4eac4fa371ca3',
    messagingSenderId: '409210327322',
    projectId: 'amlanguage-1ae39',
    storageBucket: 'amlanguage-1ae39.appspot.com',
    iosClientId: '409210327322-16ccdbv1q0bkgdo0hej7r4voeh1ul6v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
